CREATE TABLE inactivepassports (
    Id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    PASSP_SERIES smallint,
    PASSP_NUMBER integer
);

CREATE TEMP TABLE temp_inactivepassports (
    Id serial,
    PASSP_SERIES char(4),
    PASSP_NUMBER char(6)
);

COPY temp_inactivepassports (PASSP_SERIES, PASSP_NUMBER) FROM '//passportsdata//Data.csv' DELIMITER ',' CSV HEADER;

INSERT INTO inactivepassports (PASSP_SERIES, PASSP_NUMBER) SELECT CAST(PASSP_SERIES AS integer), CAST(PASSP_NUMBER AS integer) FROM temp_inactivepassports WHERE PASSP_SERIES ~ '[0-9]{4}' AND PASSP_NUMBER ~ '[0-9]{6}';