CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE inactivepassports (
    passp_series smallint NOT NULL,
    passp_number integer NOT NULL,
    active boolean NOT NULL,
    CONSTRAINT "PK_inactivepassports" PRIMARY KEY (passp_series, passp_number)
);

CREATE TABLE passporthistory (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    passp_series smallint NOT NULL,
    passp_number integer NOT NULL,
    active_start date NOT NULL,
    active_end date,
    CONSTRAINT "PK_passporthistory" PRIMARY KEY (id),
    CONSTRAINT "FK_passporthistory_inactivepassports_passp_series_passp_number" FOREIGN KEY (passp_series, passp_number) REFERENCES inactivepassports (passp_series, passp_number) ON DELETE CASCADE
);

CREATE INDEX "IX_passporthistory_passp_series_passp_number" ON passporthistory (passp_series, passp_number);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241114091013_InitialCreate', '8.0.10');

COMMIT;

