// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Passports.Database;

#nullable disable

namespace Passports.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Passports.Models.Passport", b =>
                {
                    b.Property<short>("Series")
                        .HasColumnType("smallint")
                        .HasColumnName("passp_series");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("passp_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.HasKey("Series", "Number");

                    b.ToTable("inactivepassports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
